import React from 'react';
import Footer from '../components/Footer';

const TermsConditions: React.FC = () => {
  return (
    <div className="terms-conditions-page">
      {/* Header */}
      <header className="header">
        <div className="header-container">
          <div className="logo">
            <img src="/NEW LOGO.PNG" alt="Shipsarthi" className="logo-img" />
            <span className="logo-text">Shipsarthi</span>
          </div>
        </div>
      </header>

      <div className="terms-conditions-container">
          <h1 className="page-title">Terms and Conditions</h1>
        <p className="last-updated">Effective Date: Upon registration or acceptance on the Shipsarthi Solutions platform.</p>
        <p>By accessing or using our Website or App, you agree to these Terms and Conditions ("Agreement") in full. Shipsarthi Solutions (hereinafter "Shipsarthi," "we," "our," or "Company") is a logistics management platform that connects merchants (sellers) with courier service providers, acting solely as a facilitator or marketplace. We do not sell courier services or assume liability for any courier partner's performance or quality.</p>
        <p>This Agreement is published under the Information Technology Act, 2000, as an electronic record and does not require a physical signature. If you do not agree to the terms, do not use our services.</p>
        <p>If you have questions, contact us at:</p>
        <p>📞 +91-9636369672</p>
        <p>📧 hello@shipsarthi.com</p>
        <p>🌐 www.shipsarthi.com</p>

        <div className="content-section">
          <h2>1. Scope of Services</h2>
          <h3>1.1 Services Provided</h3>
          <p>Shipsarthi Solutions provides a web and mobile platform that automates shipping logistics. We offer merchants an integrated shipping panel to book and track shipments with third-party courier vendors. All pickups and deliveries are performed by our courier partners. These services are the actual "Delivery Services." We coordinate and facilitate them on your behalf. We assign courier vendors and tracking numbers based on destination and shipment type. You understand that we are not the seller of goods. We have no direct relationship with the end customer. Our liability extends only to you, the merchant.</p>
          
          <h3>1.2 Your Responsibilities</h3>
          <p>By using our platform, you confirm you are at least 18 and allowed to enter this Agreement. You must sign up for an account and give true, complete information. By clicking "I Agree" or moving past sign-up, you agree to these terms. Do not use our Services if you do not understand or accept them. You also agree to get messages from us by email, SMS, and WhatsApp, and know these messages count as official notices.</p>
          
          <h3>1.3 Legal Compliance</h3>
          <p>Your use of Shipsarthi's platform is subject to all applicable laws, including the Information Technology Act, 2000. This Agreement is an electronic record, generated by a computer and valid under the IT Act. We may amend these terms at any time. Your continued use after changes means you accept them.</p>
        </div>

        <div className="content-section">
          <h2>2. Term and Termination</h2>
          <h3>2.1 Term</h3>
          <p>This Agreement becomes effective upon your acceptance. It continues for twelve (12) months ("Term"), unless earlier terminated. Renewal is possible by mutual consent.</p>
          
          <h3>2.2 Termination</h3>
          <p>Either party may terminate this Agreement without cause by giving thirty (30) days' written notice. Immediate termination is allowed if the other party materially breaches the Agreement and fails to cure the breach within thirty (30) days. Immediate termination is also allowed if the other party becomes insolvent, bankrupt, or ceases normal business operations.</p>
          
          <h3>2.3 Effect of Termination</h3>
          <p>Termination does not waive any rights or liabilities accrued before termination. Clauses such as confidentiality, indemnity, and limitation of liability shall survive termination. Upon termination or account closure, settle any outstanding payments must be settled promptly. We may suspend or cancel shipments in progress. You remain liable for all delivery fees and charges up to the termination date.</p>
        </div>

        <div className="content-section">
          <h2>3. Representations and Warranties</h2>
          <p>3.1 Each party represents that it has full authority to enter into and perform under this Agreement.</p>
          <p>3.2 Each party shall maintain all required licenses, approvals, and permits required to perform its obligations.</p>
          <p>3.3 Each party represents that it is solvent and not under insolvency proceedings.</p>
          <p>3.4 You warrant compliance with all laws related to your shipments, including sales, export/import, taxes, and product compliance. You are solely responsible for duties, taxes, and customs compliance. Shipsarthi does not verify your product's legality or licenses Any violation shall be your responsibility, and you shall indemnify Shipsarthi as per Section 7.</p>
        </div>

        <div className="content-section">
          <h2>4. Merchant (User) Obligations</h2>
          <ul>
            <li>Provide accurate shipment details, weights, dimensions, and ensure compliant packaging.</li>
            <li>Do not ship banned, restricted, hazardous, or illegal items (including cash, jewelry, narcotics, weapons, live animals, etc.).</li>
            <li>You are solely responsible for all product quality, legal, and refund issues with your customers.</li>
            <li>Ensure correct contact details on shipping labels.</li>
            <li>Promptly respond to customer queries and disputes.</li>
            <li>Obtain shipment insurance at your own cost.</li>
            <li>Inform us of pickup schedules and ensure shipments are ready within the agreed cut-off times.</li>
            <li>Provide signed courier manifest receipts as proof of pickup.</li>
            <li>You are solely responsible for your products; Shipsarthi is not responsible for product defects, mismatches, or counterfeit goods.</li>
            <li>Repeated non-compliance or fraudulent behavior may result in delisting or suspension.</li>
            <li>Shipsarthi reserves the right to deduct wallet balances or hold COD amounts in cases of illegal activity, misuse of services, misbehavior, rule violations, or any activity found in contravention of these Terms and Conditions.</li>
            <li>Each merchant agrees to indemnify Shipsarthi for any losses or damages arising from breach of the above obligations.</li>
          </ul>
        </div>

        <div className="content-section">
          <h2>5. Shipsarthi Obligations</h2>
          <ul>
            <li>Facilitate shipment booking, pickup, and delivery through third-party courier partners.</li>
            <li>Provide tracking and customer support tools.</li>
            <li>Not liable for delays, losses, or damages caused by courier partners.</li>
            <li>May reject incorrectly packed, mislabeled, undocumented, or prohibited shipments.</li>
            <li>COD Handling: For Cash on Delivery shipments, the courier will collect payment and remit to you as per agreed timelines, after deducting fees. Delivery is completed only after payment receipt.</li>
            <li>Coverage: We will regularly update serviceable pin codes and areas.</li>
            <li>Compliance: Shipsarthi will comply with applicable laws in providing its services.</li>
          </ul>
        </div>

        <div className="content-section">
          <h2>6. Fees and Payment Terms</h2>
          <h3>6.1 Fees</h3>
          <p>You must pay Shipsarthi all shipping fees and service charges as specified on our website or agreed in writing. Fees are exclusive of taxes. You are responsible for applicable GST or duties. Fee changes will apply prospectively after notice.</p>
          
          <h3>6.2 Invoicing</h3>
          <p>Invoices will be issued periodically (e.g., monthly) and available through your dashboard. Payments are due within 7–14 days unless otherwise agreed.</p>
          
          <h3>6.3 Late Payments</h3>
          <p>If payment is delayed, we may:</p>
          <p>(a) Adjust or withhold COD funds,</p>
          <p>(b) Charge 18% p.a. interest on overdue amounts, and/or</p>
          <p>(c) Suspend or cancel ongoing services.</p>
          <p>Disputes must be raised within 3 days of invoice receipt.</p>
          
          <h3>6.4 Security Deposit / Advance</h3>
          <p>You may need to maintain a wallet or deposit balance. Failure to maintain the balance may result in account suspension. Unused balances do not accrue interest, and transfer gateway charges may apply.</p>
          
          <h3>6.5 Taxes and Deductions</h3>
          <p>All payments must be made without set-off or deduction. You are responsible for any withholding taxes required by law.</p>
        </div>

        <div className="content-section">
          <h2>7. Liability and Indemnification</h2>
          <h3>7.1 Disclaimer</h3>
          <p>Shipsarthi provides the platform "as is," without any warranty of uninterrupted or error-free service. We disclaim all implied warranties of merchantability or fitness for a particular purpose. We are not responsible for your goods, nor are we a party to your customer transactions.</p>
          
          <h3>7.2 Limitation of Liability</h3>
          <p>Neither Shipsarthi nor its partners shall be liable for indirect, incidental, or consequential damages. Our total liability under this Agreement shall not exceed ₹2,000 (Rupees Two Thousand) or the shipment value, whichever is lower. A shipment is deemed "lost" if not delivered within 60 days of pickup (excluding force majeure events).</p>
          
          <h3>7.3 Indemnification</h3>
          <p>You agree to indemnify and hold harmless Shipsarthi, its directors, employees, and affiliates against any claims, losses, damages, or liabilities arising from your breach of this Agreement or misuse of the platform.</p>
        </div>

        <div className="content-section">
          <h2>8. Intellectual Property</h2>
          <p>All platform content, including logos, code, and designs, is Shipsarthi's exclusive property. You have a limited, non-exclusive license to use brand assets for service purposes only. You shall not copy, modify, or reverse-engineer any proprietary material. Any materials you provide, such as business data or trademarks, remain your property.</p>
        </div>

        <div className="content-section">
          <h2>9. Governing Law and Dispute Resolution</h2>
          <p>This Agreement is governed by the laws of India. Disputes will be resolved through arbitration in New Delhi, under the Arbitration and Conciliation Act, 1996, before a sole arbitrator appointed by Shipsarthi. Proceedings will be in English. Either party may seek interim injunctive relief from courts of competent jurisdiction.</p>
        </div>

        <div className="content-section">
          <h2>10. Miscellaneous</h2>
          <p>No Partnership: This Agreement does not create any partnership, joint venture, or agency.</p>
          <p>Assignment: You may not assign rights without our consent; we may assign to affiliates.</p>
          <p>Severability: Invalid provisions shall not affect the remainder.</p>
          <p>Amendments: No amendment is valid unless in writing and signed by both parties.</p>
          <p>Entire Agreement: This document constitutes the entire understanding between the parties.</p>
        </div>

        <div className="content-section">
          <h2>11. Contact Information</h2>
          <p>Shipsarthi Solutions</p>
          <p>📞 +91 9636369672</p>
          <p>📧 hello@shipsarthi.com</p>
          <p>🌐 www.shipsarthi.com</p>
          <p>Your continued use of Shipsarthi's platform constitutes acceptance of these Terms.</p>
        </div>

        <div className="content-section">
          <h2>ANNEXURE – Forward Services (Applicable to All Forward Shipments)</h2>
          <p><strong>Delivery Attempts:</strong> Shipsarthi's courier partners shall make up to three (3) delivery attempts. Unsuccessful attempts shall be updated via API. The Merchant must provide alternate instructions within 24 hours of an unsuccessful attempt. If the customer rejects the shipment on the first attempt, no further attempt will be made unless re-instructed.</p>
          
          <p><strong>Pickup Attempts:</strong> Couriers will attempt to pick up shipments up to three (3) times. Beyond this, uncollected shipments will be marked as Pickup Cancelled.</p>
          
          <p><strong>Proof of Delivery (POD):</strong> POD will be shared in case of disputes raised within 48 hours of delivery.</p>
          
          <p><strong>Tampered Packages:</strong> Couriers shall not deliver packages found tampered or damaged in transit. Customers may reject such shipments. Once delivered, no dispute claims shall be entertained.</p>
          
          <p><strong>Pickup Location:</strong> Shipments shall be picked up from merchant locations registered with Shipsarthi at the time of signup.</p>
          
          <p><strong>Tracking:</strong> Shipsarthi provides online tracking through logistics partners. Merchants must ensure shipments are ready before courier cut-off times.</p>
          
          <p><strong>Pickup Manifest:</strong> Merchants must collect signed copies of courier manifests as proof of handover.</p>
          
          <p><strong>Registered Pickup Locations:</strong> Orders will only be picked up from locations registered in the merchant panel.</p>
          
          <p><strong>Volumetric Weight:</strong> Freight will be calculated based on L×B×H/5000 for Air and L×B×H/4000 for Surface, whichever is higher between volumetric or actual weight.</p>
          
          <p><strong>COD Adjustments:</strong> If any COD amount is wrongly remitted due to erroneous delivery status, the same shall be deducted from future COD payouts or wallet balances.</p>
          
          <p><strong>✅ Final Note:</strong></p>
          <p>Shipsarthi reserves the right to hold, deduct, or adjust wallet balances or COD remittances in cases involving illegal activities, service misuse, misbehavior, non-compliance, or any act in violation of these Terms and Conditions.</p>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsConditions;
